### ISSUE TITLE
[BUG] expo version 

### ISSUE THREAD

**Issue by younes200** [agrawal-rohit/pearl-ui#161]
**Describe the bug**
First of all, thank you for the awesome lib !
I had issu with expo dependencies. 
Expo is sensitive to to duplicated unimodule packages specially for cocoa pods which was build to fail.

**To Reproduce**

    expo init --name my-app
    cd my-app
    yarn add pearl-ui
    eas build --platform ios --local 
    

```
...
[INSTALL_PODS] Found some duplicated unimodule packages. Installed the ones with the highest version number.
[INSTALL_PODS] Make sure following dependencies of your project are resolving to one specific version:
[INSTALL_PODS]  expo-file-system, expo-modules-core, expo-splash-screen
...
[INSTALL_PODS] [!] CocoaPods could not find compatible versions for pod "ExpoModulesCore":
[INSTALL_PODS]   In Podfile:
[INSTALL_PODS]     EXConstants (from `../node_modules/expo-constants/ios`) was resolved to 11.0.2, which depends on
[INSTALL_PODS]       ExpoModulesCore
[INSTALL_PODS] 
[INSTALL_PODS]     ExpoModulesCore (from `../node_modules/expo-modules-core/ios`)
[INSTALL_PODS] 
[INSTALL_PODS] Specs satisfying the `ExpoModulesCore (from `../node_modules/expo-modules-core/ios`), ExpoModulesCore` dependency were found, but they required a higher minimum deployment target.
```
    
**Expected behavior**
Build not to fail

**Smartphone (please complete the following information):**
 - Device: iPhone6
 - OS: iOS

**Possibile solution**
Moving expo dependencies as package.resolutions instead

**Comment by younes200** [comment]
This PR shows a possible fix : https://github.com/agrawal-rohit/pearl-ui/pull/162
Feel free to comment if need clarification.

**Comment by agrawal-rohit** [comment]
Hey @younes200, Thanks for bringing up the issue and attaching a PR for the same. I'll merge the PR once it passes the checks

**Comment by agrawal-rohit** [comment]
Hey @younes200, I'm re-opening this issue and reverting the merge of your PR. Doing a fresh install using the updated `package.json` in the PR is allowing incompatible versions of libraries to be installed which causes the app build to fail.

Example:
```
Warning: Invalid version react-native@0.66.4 for expo sdkVersion 44.0.0. Use react-native@0.64.3
```

Could you take a look at this and open another PR when you find a solution? Thanks
